language: objective-c
before_install:
  - gem install cocoapods
  - gem install xcpretty
script:
  - xcodebuild -project URITemplate.xcodeproj -scheme URITemplate test -sdk macosx | xcpretty -c && exit ${PIPESTATUS[0]}
  - xcodebuild -project URITemplate.xcodeproj -scheme URITemplate test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c && exit ${PIPESTATUS[0]}
