language: objective-c
before_install:
- gem install cocoapods --no-document
- gem install xcpretty --no-document
script:
- set -o pipefail
- xcodebuild -project URITemplate.xcodeproj -scheme URITemplate test -sdk macosx | xcpretty -c
- xcodebuild -project URITemplate.xcodeproj -scheme URITemplate test -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
- pod lib lint
